import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Manrope } from "next/font/google";
import { RootNavigation } from "@/components/navs/RootNavigation";
import Footer from "@/components/home/Footer";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.variable} ${manrope.variable} antialiased font-montserrat tracking-wide text-dark-700`}
            >
                <RootNavigation />
                {children}
                <Footer />
            </body>
        </html>
    );
}
